import json

with open("robustness_wording_check.ipynb", "r") as f:
    nb = json.load(f)

new_cell_lines = [
    "# === Core functions ===\n",
    "\n",
    "class NonRetryableAPIError(Exception):\n",
    "    \"\"\"Raised for errors that retrying will never fix (bad key, bad model slug, bad request).\"\"\"\n",
    "    pass\n",
    "\n",
    "\n",
    "class OpenRouterClient:\n",
    "    NON_RETRYABLE_STATUS_CODES = {400, 401, 403, 404, 422}\n",
    "\n",
    "    def __init__(self, api_key=None):\n",
    "        self.api_key = api_key or os.environ.get(\"OPENROUTER_API_KEY\")\n",
    "        if not self.api_key:\n",
    "            raise ValueError(\"No OpenRouter API key found.\")\n",
    "\n",
    "        self.client = OpenAI(\n",
    "            base_url=\"https://openrouter.ai/api/v1\",\n",
    "            api_key=self.api_key,\n",
    "            timeout=60.0,\n",
    "        )\n",
    "        self.last_call_time = 0\n",
    "        self.call_count = 0\n",
    "        self.error_count = 0\n",
    "        self.total_input_tokens = 0\n",
    "        self.total_output_tokens = 0\n",
    "        self.truncated_responses = 0\n",
    "\n",
    "    def _rate_limit_wait(self):\n",
    "        elapsed = time.time() - self.last_call_time\n",
    "        min_delay = CONFIG[\"rate_limit\"][\"min_delay_between_calls\"]\n",
    "        if elapsed < min_delay:\n",
    "            time.sleep(min_delay - elapsed)\n",
    "\n",
    "    def chat(self, messages, model, temperature=0.1, max_tokens=1024, return_finish_reason=False, reasoning=None):\n",
    "        self._rate_limit_wait()\n",
    "        for attempt in range(CONFIG[\"rate_limit\"][\"retry_max\"]):\n",
    "            try:\n",
    "                self.last_call_time = time.time()\n",
    "                self.call_count += 1\n",
    "                extra_body = {\"reasoning\": reasoning} if reasoning else {}\n",
    "                response = self.client.chat.completions.create(\n",
    "                    model=model, messages=messages, temperature=temperature, max_tokens=max_tokens,\n",
    "                    extra_body=extra_body,\n",
    "                )\n",
    "\n",
    "                if response.usage:\n",
    "                    self.total_input_tokens += response.usage.prompt_tokens or 0\n",
    "                    self.total_output_tokens += response.usage.completion_tokens or 0\n",
    "\n",
    "                finish_reason = response.choices[0].finish_reason\n",
    "                if finish_reason == \"length\":\n",
    "                    self.truncated_responses += 1\n",
    "                    logger.warning(\"Response truncated (finish_reason='length') for model=%s.\", model)\n",
    "\n",
    "                content = response.choices[0].message.content or \"\"\n",
    "                if return_finish_reason:\n",
    "                    return content, finish_reason\n",
    "                return content\n",
    "\n",
    "            except Exception as e:\n",
    "                status_code = getattr(e, \"status_code\", None)\n",
    "                if status_code in self.NON_RETRYABLE_STATUS_CODES:\n",
    "                    self.error_count += 1\n",
    "                    logger.error(\"Non-retryable error (status %s) model=%s: %s\", status_code, model, str(e)[:200])\n",
    "                    raise NonRetryableAPIError(f\"status={status_code} model={model} error={e}\") from e\n",
    "\n",
    "                delay = CONFIG[\"rate_limit\"][\"retry_base_delay\"] * (2 ** attempt) + random.uniform(0, 1)\n",
    "                logger.warning(\"API error (attempt %d/%d) model=%s. Retrying in %.1fs. Error: %s\",\n",
    "                                attempt + 1, CONFIG[\"rate_limit\"][\"retry_max\"], model, delay, str(e)[:200])\n",
    "                time.sleep(delay)\n",
    "                if attempt == CONFIG[\"rate_limit\"][\"retry_max\"] - 1:\n",
    "                    self.error_count += 1\n",
    "                    raise\n",
    "\n",
    "    def usage_summary(self):\n",
    "        total_tokens = self.total_input_tokens + self.total_output_tokens\n",
    "        # Rough gpt-oss-family estimate; check OpenRouter's dashboard for exact spend.\n",
    "        est_input_cost = (self.total_input_tokens / 1_000_000) * 0.05\n",
    "        est_output_cost = (self.total_output_tokens / 1_000_000) * 0.20\n",
    "        est_total = est_input_cost + est_output_cost\n",
    "        logger.info(\n",
    "            \"Token usage: %d input + %d output = %d total | Rough est. cost: $%.4f | Truncated: %d\",\n",
    "            self.total_input_tokens, self.total_output_tokens, total_tokens, est_total, self.truncated_responses,\n",
    "        )\n",
    "        return est_total\n",
    "\n",
    "\n",
    "def get_reasoning_config(model_id):\n",
    "    for family_name, family_models in CONFIG[\"families\"].items():\n",
    "        if model_id in family_models.values():\n",
    "            return CONFIG[\"reasoning_config\"].get(family_name)\n",
    "    logger.warning(\"get_reasoning_config: model_id=%s not recognized; sending no reasoning config.\", model_id)\n",
    "    return None\n",
    "\n",
    "\n",
    "def normalize_ground_truth(raw_value, label_map=None):\n",
    "    label_map = label_map or {}\n",
    "    if raw_value is None:\n",
    "        return None\n",
    "    raw_upper = str(raw_value).strip().upper()\n",
    "    if raw_upper in CONFIG[\"verifier_label_space\"]:\n",
    "        return raw_upper\n",
    "    raw_lower = str(raw_value).strip().lower()\n",
    "    if raw_lower in label_map:\n",
    "        return label_map[raw_lower]\n",
    "    return None\n",
    "\n",
    "\n",
    "REFUSAL_PHRASES = [\"i cannot fulfill\", \"i cannot assist\", \"unable to assist\", \"i can't help\", \"as an ai model\", \"i am unable to assist\"]\n",
    "\n",
    "\n",
    "def parse_verifier_response(response_text, initial_judgment=None):\n",
    "    \"\"\"Multi-stage parser -- handles standard JUDGMENT: format plus conversational replies.\"\"\"\n",
    "    result = {\"judgment\": None, \"confidence\": None, \"reasoning\": None, \"raw_response\": response_text}\n",
    "\n",
    "    clean_text = (response_text or \"\").replace(\"*\", \"\").replace(\"#\", \"\").strip()\n",
    "    if not clean_text:\n",
    "        return result\n",
    "\n",
    "    # Stage 1: Standard JUDGMENT: format (Check FIRST before refusal check so legal reasoning with 'cannot' is preserved)\n",
    "    m1 = re.search(r\"JUDGMENT:\s*(VALID|INVALID|UNSUPPORTED|SUPPORTED|NOT SUPPORTED)\", clean_text, re.IGNORECASE)\n",
    "    if m1:\n",
    "        raw_j = m1.group(1).upper()\n",
    "        j = \"VALID\" if raw_j == \"SUPPORTED\" else (\"UNSUPPORTED\" if raw_j == \"NOT SUPPORTED\" else raw_j)\n",
    "        m_conf = re.search(r\"CONFIDENCE:\s*(\d+)\", clean_text, re.IGNORECASE)\n",
    "        conf = int(m_conf.group(1)) if m_conf else None\n",
    "        m_reas = re.search(r\"REASONING:\s*(.+)\", clean_text, re.DOTALL | re.IGNORECASE)\n",
    "        reas = m_reas.group(1).strip() if m_reas else clean_text[:300]\n",
    "        result[\"judgment\"], result[\"confidence\"], result[\"reasoning\"] = j, conf, reas\n",
    "        return result\n",
    "\n",
    "    # Stage 2: Conversational 'judgment is VALID/INVALID'\n",
    "    m2 = re.search(r'(?:is|judgment of|verdict of|conclusion of|judgment is)\s+[\"\\\']?(VALID|INVALID|UNSUPPORTED|SUPPORTED)[\"\\\']?', clean_text, re.IGNORECASE)\n",
    "    if m2:\n",
    "        raw_j = m2.group(1).upper()\n",
    "        j = \"VALID\" if raw_j == \"SUPPORTED\" else raw_j\n",
    "        m_conf = re.search(r\"CONFIDENCE:\s*(\d+)\", clean_text, re.IGNORECASE)\n",
    "        conf = int(m_conf.group(1)) if m_conf else None\n",
    "        result[\"judgment\"], result[\"confidence\"], result[\"reasoning\"] = j, conf, clean_text[:300]\n",
    "        return result\n",
    "\n",
    "    # Check for genuine AI safety refusals only if standard judgment headers were missing\n",
    "    if any(p in clean_text.lower() for p in REFUSAL_PHRASES):\n",
    "        return result\n",
    "\n",
    "    # Stage 3: 'Stand by original judgment'\n",
    "    m3 = re.search(r'stand by (?:my )?(?:original )?judgment(?: of [\"\\\']?(VALID|INVALID|UNSUPPORTED)[\"\\\']?)?', clean_text, re.IGNORECASE)\n",
    "    if m3:\n",
    "        j = m3.group(1).upper() if m3.group(1) else initial_judgment\n",
    "        if j:\n",
    "            result[\"judgment\"], result[\"reasoning\"] = j, clean_text[:300]\n",
    "            return result\n",
    "\n",
    "    # Stage 4: Verifier maintains judgment but phrases it differently\n",
    "    if any(p in clean_text.lower() for p in [\n",
    "        \"confirmed the verifier's judgment\", \"interaction is complete\",\n",
    "        \"verifier's judgment of\", \"that's not necessary\",\n",
    "        \"you've confirmed the verifier's judgment\"\n",
    "    ]):\n",
    "        if initial_judgment:\n",
    "            result[\"judgment\"], result[\"reasoning\"] = initial_judgment, clean_text[:300]\n",
    "            return result\n",
    "\n",
    "    # Stage 5: Strong conversational indicator\n",
    "    m4 = re.search(r\"(?:therefore|thus|conclude|conclusion|judgment)\\b.{0,40}\\b(VALID|INVALID|UNSUPPORTED)\\b\", clean_text, re.IGNORECASE)\n",
    "    if m4:\n",
    "        j = m4.group(1).upper()\n",
    "        m_conf = re.search(r\"CONFIDENCE:\s*(\d+)\", clean_text, re.IGNORECASE)\n",
    "        conf = int(m_conf.group(1)) if m_conf else None\n",
    "        result[\"judgment\"], result[\"confidence\"], result[\"reasoning\"] = j, conf, clean_text[:300]\n",
    "        return result\n",
    "\n",
    "    # Stage 6: Last resort single-label fallback\n",
    "    labels_found = set()\n",
    "    for lbl in [\"VALID\", \"INVALID\", \"UNSUPPORTED\"]:\n",
    "        if re.search(r\"\\b\" + lbl + r\"\\b\", clean_text, re.IGNORECASE):\n",
    "            labels_found.add(lbl)\n",
    "    \n",
    "    if \"VALID\" in labels_found and \"INVALID\" in labels_found:\n",
    "        labels_found.remove(\"VALID\")\n",
    "        \n",
    "    if len(labels_found) == 1:\n",
    "        result[\"judgment\"] = list(labels_found)[0]\n",
    "        result[\"reasoning\"] = clean_text[:300]\n",
    "        return result\n",
    "\n",
    "    return result\n",
    "\n",
    "logger.info(\"Core functions loaded.\")\n"
]

for cell in nb["cells"]:\n",
    if cell["cell_type"] == "code":\n",
        source = "".join(cell["source"])\n",
        if "def parse_verifier_response" in source:\n",
            cell["source"] = new_cell_lines\n",

with open("robustness_wording_check.ipynb", "w") as f:\n",
    json.dump(nb, f, indent=1)\n",

print("Updated python code successfully!")
